apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-5poj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-5poj
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-5poj
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-5poj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-5poj
    spec:
      containers:
      - image: quay.io/qijing/happy-path-mphn-tenant/appstudio/dc-metro-map-5poj@sha256:391976bea5b918051afdec79d3057ba41e270b5a645a51d8c600229e422b3a9f
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
